version: "3"
services:
  
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "start"  
    ports:
      - "3000:3000"
      - "35729:35729"
    volumes: 
      - /node_modules
      - .:/app
    
  tests:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: "test"  
    volumes: 
      - /node_modules
      - .:/app