FROM node:latest

ADD package.json /package.json
RUN yarn

ENV NODE_PATH=/node_modules
ENV PATH=$PATH:/node_modules/.bin
ENV CHOKIDAR_USEPOLLING=true
ENV NODE_ENV=development

WORKDIR /app
COPY . .

EXPOSE 3000

ENTRYPOINT ["/bin/bash", "/app/run.sh"]
CMD ["start"]